services:
  - type: web
    name: rust-geolocator
    runtime: rust
    plan: free
    healthCheckPath: /swagger-ui/
    autoDeploy: true
    buildCommand: cargo build --release
    startCommand: ./target/release/rust-ip-geolocator